### ISSUE TITLE
Aufgabe5

### ISSUE THREAD

**Issue by LiudmilaKolesnikova** [gitmasterMitja/sweng-code-do-1#4]
https://drive.google.com/open?id=1qjX5ik0MbxH2HWvjYYSOLq4UhOUHHMff

**Comment by nicolemjohnson** [comment]
In the Konto classes, the attribute's name is bezeichnung. I would change konto to bezeichnung. As I understood it, a Bankbezeichnung is just the name of the bank so the String just has to be "XYZ-Bank". Just a detail but I would probably call the Geschäftskunde object malermeisterMueller after the company and not hansMüller, but you don't have to change this.

**Comment by LiudmilaKolesnikova** [comment]
Changed the name of the attribute to bezeichnung and the String to "XYZ-Bank"
